### PR TITLE
Fix trailing slash

### LINKED ISSUE #24: Take trailing slash into account

### PR DESCRIPTION
**Pull request by nojaf**
Hi @florian-lefebvre, I believe I have found a fix for #24.

The problem was only ever happening on the root of a locale without a trailing slash.
F.ex. `http://localhost:4322/fr`. 

So I remove the trailing slash in the middleware.

### CODE REVIEW

**Review by florian-lefebvre — APPROVED** [review]

**Comment by amosbastian** [comment]
Funnily enough I think this caused #38 😆

**Comment by florian-lefebvre** [comment]
Yeah that's likely, if you find how to fix it I take it :laughing:

File: package/assets/middleware.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ const extractLocaleFromUrl = (pathname: string) => {
 		} else if (options.strategy === "prefixExceptDefault") {
 			if (
 				locale !== options.defaultLocale &&
-				pathname.startsWith(`/${locale}/`)
+				pathname.startsWith(`/${locale}`)
```
Comment (nojaf) [inline package/assets/middleware.ts:14]: @amosbastian perhaps you can try to use 

```js
const locale = 'fr';
const regex = new RegExp(`^/${locale}(/|$|/[^/]+)`);

console.log(regex.test('/fr'));      // true
console.log(regex.test('/fr/'));     // true
console.log(regex.test('/fr/boo'));  // true
console.log(regex.test('/freedom')); // false
```

instead of `pathname.startsWith`
